### ISSUE TITLE
Exception trying to sign transaction

### ISSUE THREAD

**Issue by avive** [spacemeshos/ledger-sdk#1]
I'm getting this error when trying to sign a transaction with alpha release (both sdk and app) using the sdk's node test app. The other test functions pass.

```
signCoinTx
TypeError: data.writeBigUInt64BE is not a function
    at Object.uint64_to_buf (/home/parallels/dev/ledger-sdk/lib/utils.js:114:8)
    at _callee5$ (/home/parallels/dev/ledger-sdk/example-node/lib/index.js:154:30)
    at tryCatch (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/parallels/dev/ledger-sdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
```

**Comment by avive** [comment]
Please add min required node version. Issue seems to be an older version of node.
